package stt

import (
	"errors"
)

var (
	ErrInvalidAudio                        = errors.New("invalid audio")
	ErrUnsupportedFormat                   = errors.New("unsupported audio format")
	ErrInvalidFeatureConfig                = errors.New("invalid feature configuration")
	ErrFeatureExtraction                   = errors.New("feature extraction failed")
	ErrEmptyVocabulary                     = errors.New("empty vocabulary")
	ErrUnknownToken                        = errors.New("unknown token")
	ErrInvalidToken                        = errors.New("invalid token")
	ErrInvalidDataset                      = errors.New("invalid dataset")
	ErrEmptyDataset                        = errors.New("empty dataset")
	ErrInvalidWAV                          = errors.New("invalid wav")
	ErrUnsupportedWAV                      = errors.New("unsupported wav format")
	ErrInvalidManifest                     = errors.New("invalid manifest")
	ErrManifestLine                        = errors.New("invalid manifest line")
	ErrInvalidDatasetLoader                = errors.New("invalid dataset loader")
	ErrInvalidBatch                        = errors.New("invalid batch")
	ErrEmptyBatch                          = errors.New("empty batch")
	ErrBatchSizeInvalid                    = errors.New("invalid batch size")
	ErrInvalidTensor                       = errors.New("invalid tensor")
	ErrTensorIndex                         = errors.New("tensor index out of range")
	ErrInvalidLinear                       = errors.New("invalid linear layer")
	ErrLinearInput                         = errors.New("invalid linear input")
	ErrInvalidLSTM                         = errors.New("invalid lstm")
	ErrLSTMInput                           = errors.New("invalid lstm input")
	ErrInvalidLSTMSequence                 = errors.New("invalid lstm sequence")
	ErrInvalidBiLSTM                       = errors.New("invalid bilstm")
	ErrInvalidSTTModel                     = errors.New("invalid stt model")
	ErrInvalidCTCDecoder                   = errors.New("invalid ctc decoder")
	ErrInvalidCTCLoss                      = errors.New("invalid ctc loss")
	ErrInvalidCTCBatchLoss                 = errors.New("invalid ctc batch loss")
	ErrInvalidCTCGradient                  = errors.New("invalid ctc gradient")
	ErrInvalidLinearBackward               = errors.New("invalid linear backward")
	ErrInvalidLSTMBackward                 = errors.New("invalid lstm backward")
	ErrInvalidLSTMSequenceBackward         = errors.New("invalid lstm sequence backward")
	ErrInvalidBackwardLSTMSequenceBackward = errors.New("invalid backward lstm sequence backward")
	ErrInvalidBiLSTMBackward               = errors.New("invalid bilstm backward")
	ErrInvalidSTTModelBackward             = errors.New("invalid stt model backward")
	ErrInvalidBackwardLSTM                 = errors.New("invalid backward lstm")
	ErrInvalidSTTTraining                  = errors.New("invalid stt training")
	ErrInvalidTrainer                      = errors.New("invalid trainer")
	ErrInvalidSTTTrainingIntegration       = errors.New("invalid stt training integration")
	ErrEmptyTrainingDataset                = errors.New("empty training dataset")
	ErrInvalidOptimizer                    = errors.New("invalid optimizer")
	ErrInvalidParameter                    = errors.New("invalid parameter")
	ErrInvalidModelFile                    = errors.New("invalid model file")
	ErrInvalidLearningRate                 = errors.New("invalid learning rate")
	ErrInvalidAdam                         = errors.New("invalid adam")
	ErrInvalidDataLoader                   = errors.New("invalid data loader")
	ErrInvalidCER                          = errors.New("invalid cer input")
	ErrDataLoaderDone                      = errors.New("data loader exhausted")
	ErrInvalidDatasetSplit                 = errors.New("invalid dataset split")
	ErrInvalidEarlyStopping                = errors.New("invalid early stopping")
	ErrInvalidTrainingCheckpoint           = errors.New("invalid training checkpoint")
	ErrInvalidMetricInput                  = errors.New("invalid metric input")
	ErrInvalidTrainingConfig               = errors.New("invalid training config")
	ErrInvalidLocalSTT                     = errors.New("invalid local stt")
	ErrEmptyAudio                          = errors.New("empty audio")
	ErrInvalidCommonVoice                  = errors.New("invalid common voice dataset")
	ErrCommonVoiceAudio                    = errors.New("common voice audio not found")
	ErrInvalidCommonVoiceImporter          = errors.New("invalid common voice importer")
	ErrCommonVoiceManifest                 = errors.New("invalid common voice manifest")
	ErrInvalidCommonVoiceSplit             = errors.New("invalid common voice split")
	ErrCommonVoiceColumn                   = errors.New("required common voice column not found")
)

const BlankToken = "<blank>"
